language: php

env:
  global:
    - DEPENDENCIES=""

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DEPENDENCIES="low"

before_install:
  - composer self-update

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-source --prefer-lowest; fi
  - if [ "$DEPENDENCIES" != "low" ]; then composer install --prefer-source; fi
